site_name: aGoodShoemaker

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.top
        - header.autohide
markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - toc:
          permalink: true
    - def_list
    - attr_list
    - md_in_html
    - meta
    - admonition
    - pymdownx.details
    - pymdownx.superfences
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
